templates:
  word:
    0: Vyplatka.docx
    
  excel:
    0: Hra

macros: 
  0: malware_download.txt
  1: reverse_shell.txt

app:
  malware_url: http://www.kyberakadenia.sk/login_email
  reverse_shell_ip: "127.0.0.1"